apiVersion: v1
kind: Service
metadata:
  name: phrase-svc
  labels:
    app: phrase
  {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.phrase.type }}
  selector:
    app: phrase
  {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.phrase.ports | toYaml | nindent 2 -}}