config:
  postgresDb: postgresdb
  postgresPassword: admin
  postgresUser: admin
kubernetesClusterDomain: cluster.local
postgres:
  ports:
    - port: 5432
      targetPort: 5432
  postgres:
    image:
      repository: postgres
      tag: "10.1"
    imagePullPolicy: IfNotPresent
  replicas: 1
  type: NodePort
pvc:
  pvClaim:
    storageClass: manual
    storageRequest: 5Gi
