apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.fullname" . }}-pv-volume
  labels:
    app: postgres
    type: local
  {{- include "postgres.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}-pv-claim
  labels:
    app: postgres
  {{- include "postgres.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.pvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.pvClaim.storageClass | quote }}