apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-config
  labels:
    app: postgres
  {{- include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
  POSTGRES_PASSWORD: {{ .Values.config.postgresPassword | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}