apiVersion: v1
kind: Pod
metadata:
  name: {{ include "redis.fullname" . }}-redis
  labels:
  {{- include "redis.labels" . | nindent 4 }}
spec:
  containers:
  - command:
    - redis-server
    - /redis-master/redis.conf
    env:
    - name: MASTER
      value: "true"
    image: redis:latest
    name: redis
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
  - emptyDir: {}
    name: data
  - configMap:
      items:
      - key: redis-config
        path: redis.conf
      name: redis-config
    name: config