---
# tasks file for loadbalancing_ssl

- import_role: name=ome.ssl_certificate

- name: install nginx
  ansible.builtin.apt:
    name: nginx

- name: Copy the ingress files
  ansible.builtin.copy:
    src: phrase-nginx
    dest: /etc/nginx/sites-enabled/phrase
  notify:
    - restart nginx

- name: Copy the ingress files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /tmp
  with_items:
    - ingress.sh
    - ingress.yml

- name: Deploy Ingress
  ansible.builtin.shell: sh /tmp/ingress.sh > /tmp/ingress_output.log
  when: kind_cluster_check is defined
